---
language: node_js
node_js:
  - 17
install:
  - npm install
branches:
  only:
    - travis
cache:
  directories:
    - node_modules
env:
  global:
    - NODE_ENV=test
script:
  - npm run test
deploy:
  provider: heroku
  api_key: 1375d4a6-59bc-42b4-9d80-1410120a23ce
  app: project-management-mean
